# Generated by Django 4.2.11 on 2024-04-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usre',
            new_name='user',
        ),
    ]
